// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVoBPVUt2clZlHwHHLyex66OY1LMMyjvY',
    appId: '1:489460851101:web:41a020bb9ebb03bc058f74',
    messagingSenderId: '489460851101',
    projectId: 'studyverse-51b30',
    authDomain: 'studyverse-51b30.firebaseapp.com',
    storageBucket: 'studyverse-51b30.firebasestorage.app',
    measurementId: 'G-V3KQNJ26NR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnr9purP3JSCURKD7Da9Cdn0C3OpzbJsI',
    appId: '1:489460851101:android:b72e34d3cdebe078058f74',
    messagingSenderId: '489460851101',
    projectId: 'studyverse-51b30',
    storageBucket: 'studyverse-51b30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPgYNmpRdYIsQ7UQhYA2Mt_YrsJ9VKFvg',
    appId: '1:489460851101:ios:e1b74dc756dcb979058f74',
    messagingSenderId: '489460851101',
    projectId: 'studyverse-51b30',
    storageBucket: 'studyverse-51b30.firebasestorage.app',
    iosBundleId: 'com.example.studyVerse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPgYNmpRdYIsQ7UQhYA2Mt_YrsJ9VKFvg',
    appId: '1:489460851101:ios:ff04db3f85eeeef7058f74',
    messagingSenderId: '489460851101',
    projectId: 'studyverse-51b30',
    storageBucket: 'studyverse-51b30.firebasestorage.app',
    iosBundleId: 'com.main.studyverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVoBPVUt2clZlHwHHLyex66OY1LMMyjvY',
    appId: '1:489460851101:web:8a3bb4b360bde779058f74',
    messagingSenderId: '489460851101',
    projectId: 'studyverse-51b30',
    authDomain: 'studyverse-51b30.firebaseapp.com',
    storageBucket: 'studyverse-51b30.firebasestorage.app',
    measurementId: 'G-D53QXKL29S',
  );

}